2020-07-23 19:38:15,328 INFO: Microblog startup [in /Users/robbymoseley/Desktop/MobProgramming-SocialBlog/app/__init__.py:43]
2020-07-23 19:38:23,389 INFO: Microblog startup [in /Users/robbymoseley/Desktop/MobProgramming-SocialBlog/app/__init__.py:43]
2020-07-23 19:45:06,306 INFO: Microblog startup [in /Users/robbymoseley/Desktop/MobProgramming-SocialBlog/app/__init__.py:43]
2020-07-23 19:46:11,962 INFO: Microblog startup [in /Users/robbymoseley/Desktop/MobProgramming-SocialBlog/app/__init__.py:43]
2020-07-23 19:49:07,996 INFO: Microblog startup [in /Users/robbymoseley/Desktop/MobProgramming-SocialBlog/app/__init__.py:43]
2020-07-23 19:49:49,708 INFO: Microblog startup [in /Users/robbymoseley/Desktop/MobProgramming-SocialBlog/app/__init__.py:43]
2020-07-23 19:50:10,878 INFO: Microblog startup [in /Users/robbymoseley/Desktop/MobProgramming-SocialBlog/app/__init__.py:43]
2020-07-23 19:52:00,874 INFO: Microblog startup [in /Users/robbymoseley/Desktop/MobProgramming-SocialBlog/app/__init__.py:44]
2020-07-23 19:53:06,696 INFO: Microblog startup [in /Users/robbymoseley/Desktop/MobProgramming-SocialBlog/app/__init__.py:44]
2020-07-23 19:55:12,418 INFO: Microblog startup [in /Users/robbymoseley/Desktop/MobProgramming-SocialBlog/app/__init__.py:44]
2020-07-23 19:55:45,539 ERROR: Exception on /register [POST] [in /Users/robbymoseley/Desktop/MobProgramming-SocialBlog/.venv/lib/python3.7/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/Users/robbymoseley/Desktop/MobProgramming-SocialBlog/.venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1278, in _execute_context
    cursor, statement, parameters, context
  File "/Users/robbymoseley/Desktop/MobProgramming-SocialBlog/.venv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such table: user

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/robbymoseley/Desktop/MobProgramming-SocialBlog/.venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/robbymoseley/Desktop/MobProgramming-SocialBlog/.venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/robbymoseley/Desktop/MobProgramming-SocialBlog/.venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/robbymoseley/Desktop/MobProgramming-SocialBlog/.venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/robbymoseley/Desktop/MobProgramming-SocialBlog/.venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/robbymoseley/Desktop/MobProgramming-SocialBlog/.venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/robbymoseley/Desktop/MobProgramming-SocialBlog/app/routes.py", line 84, in register
    if form.validate_on_submit():
  File "/Users/robbymoseley/Desktop/MobProgramming-SocialBlog/.venv/lib/python3.7/site-packages/flask_wtf/form.py", line 100, in validate_on_submit
    return self.is_submitted() and self.validate()
  File "/Users/robbymoseley/Desktop/MobProgramming-SocialBlog/.venv/lib/python3.7/site-packages/wtforms/form.py", line 318, in validate
    return super(Form, self).validate(extra)
  File "/Users/robbymoseley/Desktop/MobProgramming-SocialBlog/.venv/lib/python3.7/site-packages/wtforms/form.py", line 150, in validate
    if not field.validate(self, extra):
  File "/Users/robbymoseley/Desktop/MobProgramming-SocialBlog/.venv/lib/python3.7/site-packages/wtforms/fields/core.py", line 226, in validate
    stop_validation = self._run_validation_chain(form, chain)
  File "/Users/robbymoseley/Desktop/MobProgramming-SocialBlog/.venv/lib/python3.7/site-packages/wtforms/fields/core.py", line 246, in _run_validation_chain
    validator(form, self)
  File "/Users/robbymoseley/Desktop/MobProgramming-SocialBlog/app/forms.py", line 25, in validate_username
    user = User.query.filter_by(username=username.data).first()
  File "/Users/robbymoseley/Desktop/MobProgramming-SocialBlog/.venv/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3397, in first
    ret = list(self[0:1])
  File "/Users/robbymoseley/Desktop/MobProgramming-SocialBlog/.venv/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3171, in __getitem__
    return list(res)
  File "/Users/robbymoseley/Desktop/MobProgramming-SocialBlog/.venv/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3503, in __iter__
    return self._execute_and_instances(context)
  File "/Users/robbymoseley/Desktop/MobProgramming-SocialBlog/.venv/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3528, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/Users/robbymoseley/Desktop/MobProgramming-SocialBlog/.venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1014, in execute
    return meth(self, multiparams, params)
  File "/Users/robbymoseley/Desktop/MobProgramming-SocialBlog/.venv/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/Users/robbymoseley/Desktop/MobProgramming-SocialBlog/.venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1133, in _execute_clauseelement
    distilled_params,
  File "/Users/robbymoseley/Desktop/MobProgramming-SocialBlog/.venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1318, in _execute_context
    e, statement, parameters, cursor, context
  File "/Users/robbymoseley/Desktop/MobProgramming-SocialBlog/.venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1512, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/Users/robbymoseley/Desktop/MobProgramming-SocialBlog/.venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/Users/robbymoseley/Desktop/MobProgramming-SocialBlog/.venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1278, in _execute_context
    cursor, statement, parameters, context
  File "/Users/robbymoseley/Desktop/MobProgramming-SocialBlog/.venv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: user
[SQL: SELECT user.id AS user_id, user.username AS user_username, user.email AS user_email, user.password_hash AS user_password_hash, user.about_me AS user_about_me, user.last_seen AS user_last_seen 
FROM user 
WHERE user.username = ?
 LIMIT ? OFFSET ?]
[parameters: ('robby', 1, 0)]
(Background on this error at: http://sqlalche.me/e/13/e3q8)
2020-07-23 19:57:11,440 INFO: Microblog startup [in /Users/robbymoseley/Desktop/MobProgramming-SocialBlog/app/__init__.py:44]
